STATE_REQUEST_KEY = "session"
STATE_RESPONSE_KEY = "session_state"

QUESTION_TYPE = "question_type"
PREVIOUS_SCENE = "previous"
QUESTION_ID = "question_id"

MUST_BE_SAVE = [QUESTION_TYPE, PREVIOUS_SCENE, QUESTION_ID]
