STATE_REQUEST_KEY = "session"
STATE_RESPONSE_KEY = "session_state"

QUESTION_TYPE = "question_type"
PREVIOUS_SCENE = "previous"
QUESTION_ID = "question_id"
ASKED_QUESTIONS = "asked_questions"
MUST_BE_SAVE = [QUESTION_TYPE, PREVIOUS_SCENE, QUESTION_ID]
PERMANENT_VALUES = {ASKED_QUESTIONS}
TOUR_ID = "tour_id"
TOUR_LEVEL = "tour_level"
