name: Push and Deploy Serverless function
on: 
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: goodsmileduck/yandex-serverless-action@v1
      if
      with:
        token: ${{ secrets.YAAUTH }}
        function_id: ${{ secrets.GUIDE_ID }}
        runtime: 'python37-preview'
        memory: '128'
        environment: DEBUG=False
        entrypoint: 'guide.main.handler'
        source: '.'
        exclude: './guide/tests'
