name: Alice skill

on:
  push:
    branches-ignore: [ main ]
  pull_request:
    branches: [ main ]
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Python Code Quality and Lint
      uses: ricardochaves/python-lint@v1.3.0
      with:
        use-pylint: false
        use-pycodestyle: true
        use-flake8: false
        use-black: false
        use-mypy: false
        use-isort: false
        extra-pylint-options: ""
        extra-pycodestyle-options: "--exclude=tests --max-line-length=120"
        extra-flake8-options: ""
        extra-black-options: ""
        extra-mypy-options: ""
        extra-isort-options: ""
    - name: Test with pytest
      run: |
        pytest
  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: goodsmileduck/yandex-serverless-action@v1
        with:
          token: ${{ secrets.YAAUTH }}
          function_id: ${{ secrets.GUIDE_TEST_ID }}
          runtime: 'python37-preview'
          memory: '128'
          environment: DEBUG=True
          entrypoint: 'guide.main.handler'
          source: '.'
          exclude: './guide/tests'
